#!/usr/bin/env bash
echo "---- top_p = 0.95-------"
python src/scripts/run.py -env "vqa" -max_len 10 -data_path "data/vqa-v2" -out_path "output/RL/VQA_exp_size_smallvocab_vilbert" -model "lstm" -update_every 128 -agent "PPO" -K_epochs 20 -eps_clip 0.02 -lr 0.001 -word_emb_size 512 -hidden_size 1024 -num_episodes_train 30000 -debug "0,2000" -lm_path "output/vqa_lm_model_smallvocab/model.pt" -reward "vilbert" -reward_vocab "output/vilbert_vqav2/bert_base_6layer_6conect.json" -reward_path "output/vilbert_vqav2/model.bin" -num_episodes_test 100 -mask_answers 1 -truncate_mode "top_p" -grad_clip 1 -fusion "average" -condition_answer "after_fusion" -device_id 2 -min_data 1 -top_p 0.95
python src/scripts/run.py -env "vqa" -max_len 10 -data_path "data/vqa-v2" -out_path "output/RL/VQA_exp_size_smallvocab_vilbert" -model "lstm" -update_every 128 -agent "PPO" -K_epochs 20 -eps_clip 0.02 -lr 0.001 -word_emb_size 512 -hidden_size 1024 -num_episodes_train 30000 -debug "0,2000" -lm_path "output/vqa_lm_model_smallvocab/model.pt" -reward "vilbert" -reward_vocab "output/vilbert_vqav2/bert_base_6layer_6conect.json" -reward_path "output/vilbert_vqav2/model.bin" -num_episodes_test 100 -mask_answers 1 -truncate_mode "top_p" -grad_clip 1 -fusion "average" -condition_answer "after_fusion" -device_id 2 -min_data 1 -temperature 2 -temp_step 2500 -temp_factor 0.75 -temp_min 0.7 -top_p 0.95
python src/scripts/run.py -env "vqa" -max_len 10 -data_path "data/vqa-v2" -out_path "output/RL/VQA_exp_size_smallvocab_vilbert" -model "lstm" -update_every 128 -agent "PPO" -K_epochs 20 -eps_clip 0.02 -lr 0.00001 -word_emb_size 512 -hidden_size 1024 -num_episodes_train 30000 -debug "0,2000" -lm_path "output/vqa_lm_model_smallvocab/model.pt" -reward "vilbert" -reward_vocab "output/vilbert_vqav2/bert_base_6layer_6conect.json" -reward_path "output/vilbert_vqav2/model.bin" -num_episodes_test 100 -mask_answers 1 -truncate_mode "top_p" -grad_clip 1 -fusion "average" -condition_answer "after_fusion" -device_id 2 -min_data 1 -temperature 2 -temp_step 2500 -temp_factor 0.75 -temp_min 0.7 -top_p 0.95
echo "----p_th = 0.9-------"
python src/scripts/run.py -env "vqa" -max_len 10 -data_path "data/vqa-v2" -out_path "output/RL/VQA_exp_size_smallvocab_vilbert" -model "lstm" -update_every 128 -agent "PPO" -K_epochs 20 -eps_clip 0.02 -lr 0.001 -word_emb_size 512 -hidden_size 1024 -num_episodes_train 30000 -debug "0,2000" -lm_path "output/vqa_lm_model_smallvocab/model.pt" -reward "vilbert" -reward_vocab "output/vilbert_vqav2/bert_base_6layer_6conect.json" -reward_path "output/vilbert_vqav2/model.bin" -num_episodes_test 100 -mask_answers 1 -truncate_mode "top_p" -grad_clip 1 -fusion "average" -condition_answer "after_fusion" -device_id 2 -min_data 1 -top_p 0.9
python src/scripts/run.py -env "vqa" -max_len 10 -data_path "data/vqa-v2" -out_path "output/RL/VQA_exp_size_smallvocab_vilbert" -model "lstm" -update_every 128 -agent "PPO" -K_epochs 20 -eps_clip 0.02 -lr 0.001 -word_emb_size 512 -hidden_size 1024 -num_episodes_train 30000 -debug "0,2000" -lm_path "output/vqa_lm_model_smallvocab/model.pt" -reward "vilbert" -reward_vocab "output/vilbert_vqav2/bert_base_6layer_6conect.json" -reward_path "output/vilbert_vqav2/model.bin" -num_episodes_test 100 -mask_answers 1 -truncate_mode "top_p" -grad_clip 1 -fusion "average" -condition_answer "after_fusion" -device_id 2 -min_data 1 -temperature 2 -temp_step 2500 -temp_factor 0.75 -temp_min 0.7 -top_p 0.9
python src/scripts/run.py -env "vqa" -max_len 10 -data_path "data/vqa-v2" -out_path "output/RL/VQA_exp_size_smallvocab_vilbert" -model "lstm" -update_every 128 -agent "PPO" -K_epochs 20 -eps_clip 0.02 -lr 0.00001 -word_emb_size 512 -hidden_size 1024 -num_episodes_train 30000 -debug "0,2000" -lm_path "output/vqa_lm_model_smallvocab/model.pt" -reward "vilbert" -reward_vocab "output/vilbert_vqav2/bert_base_6layer_6conect.json" -reward_path "output/vilbert_vqav2/model.bin" -num_episodes_test 100 -mask_answers 1 -truncate_mode "top_p" -grad_clip 1 -fusion "average" -condition_answer "after_fusion" -device_id 2 -min_data 1 -temperature 2 -temp_step 2500 -temp_factor 0.75 -temp_min 0.7 -top_p 0.9
echo "----top_p = 0.8-------"
python src/scripts/run.py -env "vqa" -max_len 10 -data_path "data/vqa-v2" -out_path "output/RL/VQA_exp_size_smallvocab_vilbert" -model "lstm" -update_every 128 -agent "PPO" -K_epochs 20 -eps_clip 0.02 -lr 0.001 -word_emb_size 512 -hidden_size 1024 -num_episodes_train 30000 -debug "0,2000" -lm_path "output/vqa_lm_model_smallvocab/model.pt" -reward "vilbert" -reward_vocab "output/vilbert_vqav2/bert_base_6layer_6conect.json" -reward_path "output/vilbert_vqav2/model.bin" -num_episodes_test 100 -mask_answers 1 -truncate_mode "top_p" -grad_clip 1 -fusion "average" -condition_answer "after_fusion" -device_id 2 -min_data 1 -top_p 0.8
python src/scripts/run.py -env "vqa" -max_len 10 -data_path "data/vqa-v2" -out_path "output/RL/VQA_exp_size_smallvocab_vilbert" -model "lstm" -update_every 128 -agent "PPO" -K_epochs 20 -eps_clip 0.02 -lr 0.001 -word_emb_size 512 -hidden_size 1024 -num_episodes_train 30000 -debug "0,2000" -lm_path "output/vqa_lm_model_smallvocab/model.pt" -reward "vilbert" -reward_vocab "output/vilbert_vqav2/bert_base_6layer_6conect.json" -reward_path "output/vilbert_vqav2/model.bin" -num_episodes_test 100 -mask_answers 1 -truncate_mode "top_p" -grad_clip 1 -fusion "average" -condition_answer "after_fusion" -device_id 2 -min_data 1 -temperature 2 -temp_step 2500 -temp_factor 0.75 -temp_min 0.7 -top_p 0.8
python src/scripts/run.py -env "vqa" -max_len 10 -data_path "data/vqa-v2" -out_path "output/RL/VQA_exp_size_smallvocab_vilbert" -model "lstm" -update_every 128 -agent "PPO" -K_epochs 20 -eps_clip 0.02 -lr 0.00001 -word_emb_size 512 -hidden_size 1024 -num_episodes_train 30000 -debug "0,2000" -lm_path "output/vqa_lm_model_smallvocab/model.pt" -reward "vilbert" -reward_vocab "output/vilbert_vqav2/bert_base_6layer_6conect.json" -reward_path "output/vilbert_vqav2/model.bin" -num_episodes_test 100 -mask_answers 1 -truncate_mode "top_p" -grad_clip 1 -fusion "average" -condition_answer "after_fusion" -device_id 2 -min_data 1 -temperature 2 -temp_step 2500 -temp_factor 0.75 -temp_min 0.7 -top_p 0.9