#!/bin/bash
echo "-------------------------- sample-va 20 - eps 0.1---------------------------------------------------------------------------------------------------"
python src/scripts/run.py -max_len 40 -data_path "data" -out_path "output/RL/exp_clvr_vqa_20000img" -model "lstm" -update_every 128 -agent "PPO" -K_epochs 20 -eps_clip 0.02 -lr 0.001 -word_emb_size 32 -hidden_size 64 -num_episodes_train 100000 -debug "0,20000" -lm_path "output/lm_model/model.pt" -reward "vqa" -reward_path "output/vqa_model_film/model.pt" -condition_answer "after_fusion" -num_episodes_test 500 -reward_vocab "data/closure_vocab.json" -mask_answers 1 -truncate_mode "sample_va" -num_truncated 20 -grad_clip 1 -epsilon_truncated 0.1
echo "-------------------------- proba_thr0.05 - eps 0.1---------------------------------------------------------------------------------------------------"
python src/scripts/run.py -max_len 40 -data_path "data" -out_path "output/RL/exp_clvr_vqa_20000img" -model "lstm" -update_every 128 -agent "PPO" -K_epochs 20 -eps_clip 0.02 -lr 0.001 -word_emb_size 32 -hidden_size 64 -num_episodes_train 100000 -debug "0,20000" -lm_path "output/lm_model/model.pt" -reward "vqa" -reward_path "output/vqa_model_film/model.pt" -condition_answer "after_fusion" -num_episodes_test 500 -reward_vocab "data/closure_vocab.json" -mask_answers 1 -truncate_mode "proba_thr" -p_th 0.05 -grad_clip 1 -epsilon_truncated 0.1
echo "-------------------------- sample-va 20 - eps 0.2---------------------------------------------------------------------------------------------------"
python src/scripts/run.py -max_len 40 -data_path "data" -out_path "output/RL/exp_clvr_vqa_20000img" -model "lstm" -update_every 128 -agent "PPO" -K_epochs 20 -eps_clip 0.02 -lr 0.001 -word_emb_size 32 -hidden_size 64 -num_episodes_train 100000 -debug "0,20000" -lm_path "output/lm_model/model.pt" -reward "vqa" -reward_path "output/vqa_model_film/model.pt" -condition_answer "after_fusion" -num_episodes_test 500 -reward_vocab "data/closure_vocab.json" -mask_answers 1 -truncate_mode "sample_va" -num_truncated 20 -grad_clip 1 -epsilon_truncated 0.2
echo "-------------------------- proba_thr0.05 - eps 0.2---------------------------------------------------------------------------------------------------"
python src/scripts/run.py -max_len 40 -data_path "data" -out_path "output/RL/exp_clvr_vqa_20000img" -model "lstm" -update_every 128 -agent "PPO" -K_epochs 20 -eps_clip 0.02 -lr 0.001 -word_emb_size 32 -hidden_size 64 -num_episodes_train 100000 -debug "0,20000" -lm_path "output/lm_model/model.pt" -reward "vqa" -reward_path "output/vqa_model_film/model.pt" -condition_answer "after_fusion" -num_episodes_test 500 -reward_vocab "data/closure_vocab.json" -mask_answers 1 -truncate_mode "proba_thr" -p_th 0.05 -grad_clip 1 -epsilon_truncated 0.2

