#!/bin/bash
echo "-------------------------- CLEVR LM model ---------------------------------------------------------------------------------------------------"
python src/scripts/run.py -max_len 40 -data_path "data" -out_path "output/RL/exp_clvr_vqa_baselines" -model "lstm" -update_every 128 -agent "PPO" -K_epochs 20 -eps_clip 0.02 -lr 0.001 -word_emb_size 32 -hidden_size 64 -num_episodes_train 0 -debug "0,20000" -lm_path "output/lm_model/model.pt" -reward "vqa" -reward_path "output/vqa_model_film/model.pt" -condition_answer "after_fusion" -num_episodes_test 500 -reward_vocab "data/closure_vocab.json" -mask_answers 1 -alpha_logits 1
echo "-------------------------- Pretrained Policy ---------------------------------------------------------------------------------------------------"
python src/scripts/run.py -max_len 40 -data_path "data" -out_path "output/RL/exp_clvr_vqa_baselines" -model "lstm" -update_every 128 -agent "PPO" -K_epochs 20 -eps_clip 0.02 -lr 0.001 -word_emb_size 32 -hidden_size 64 -num_episodes_train 0 -debug "0,20000" -lm_path "output/lm_model/model.pt" -reward "vqa" -reward_path "output/vqa_model_film/model.pt" -condition_answer "after_fusion" -num_episodes_test 500 -reward_vocab "data/closure_vocab.json" -mask_answers 1 -policy_path "output/SL_LSTM_32_64_vqa/model.pt"
echo "-------------------------- top_p 0.9---------------------------------------------------------------------------------------------------"
python src/scripts/run.py -max_len 40 -data_path "data" -out_path "output/RL/exp_clvr_vqa_20000img_top_p" -model "lstm" -update_every 128 -agent "PPO" -K_epochs 20 -eps_clip 0.02 -lr 0.001 -word_emb_size 32 -hidden_size 64 -num_episodes_train 30000 -debug "0,20000" -lm_path "output/lm_model/model.pt" -reward "vqa" -reward_path "output/vqa_model_film/model.pt" -condition_answer "after_fusion" -num_episodes_test 500 -reward_vocab "data/closure_vocab.json" -mask_answers 1 -truncate_mode "top_p" -top_p 0.9 -grad_clip 1
echo "-------------------------- top_p 0.8---------------------------------------------------------------------------------------------------"
python src/scripts/run.py -max_len 40 -data_path "data" -out_path "output/RL/exp_clvr_vqa_20000img_top_p" -model "lstm" -update_every 128 -agent "PPO" -K_epochs 20 -eps_clip 0.02 -lr 0.001 -word_emb_size 32 -hidden_size 64 -num_episodes_train 30000 -debug "0,20000" -lm_path "output/lm_model/model.pt" -reward "vqa" -reward_path "output/vqa_model_film/model.pt" -condition_answer "after_fusion" -num_episodes_test 500 -reward_vocab "data/closure_vocab.json" -mask_answers 1 -truncate_mode "top_p" -top_p 0.8 -grad_clip 1
echo "-------------------------- top_p 0.7---------------------------------------------------------------------------------------------------"
python src/scripts/run.py -max_len 40 -data_path "data" -out_path "output/RL/exp_clvr_vqa_20000img_top_p" -model "lstm" -update_every 128 -agent "PPO" -K_epochs 20 -eps_clip 0.02 -lr 0.001 -word_emb_size 32 -hidden_size 64 -num_episodes_train 30000 -debug "0,20000" -lm_path "output/lm_model/model.pt" -reward "vqa" -reward_path "output/vqa_model_film/model.pt" -condition_answer "after_fusion" -num_episodes_test 500 -reward_vocab "data/closure_vocab.json" -mask_answers 1 -truncate_mode "top_p" -top_p 0.7 -grad_clip 1
echo "-------------------------- top_p 0.6---------------------------------------------------------------------------------------------------"
python src/scripts/run.py -max_len 40 -data_path "data" -out_path "output/RL/exp_clvr_vqa_20000img_top_p" -model "lstm" -update_every 128 -agent "PPO" -K_epochs 20 -eps_clip 0.02 -lr 0.001 -word_emb_size 32 -hidden_size 64 -num_episodes_train 30000 -debug "0,20000" -lm_path "output/lm_model/model.pt" -reward "vqa" -reward_path "output/vqa_model_film/model.pt" -condition_answer "after_fusion" -num_episodes_test 500 -reward_vocab "data/closure_vocab.json" -mask_answers 1 -truncate_mode "top_p" -top_p 0.6 -grad_clip 1
echo "-------------------------- top_p 0.5---------------------------------------------------------------------------------------------------"
python src/scripts/run.py -max_len 40 -data_path "data" -out_path "output/RL/exp_clvr_vqa_20000img_top_p" -model "lstm" -update_every 128 -agent "PPO" -K_epochs 20 -eps_clip 0.02 -lr 0.001 -word_emb_size 32 -hidden_size 64 -num_episodes_train 30000 -debug "0,20000" -lm_path "output/lm_model/model.pt" -reward "vqa" -reward_path "output/vqa_model_film/model.pt" -condition_answer "after_fusion" -num_episodes_test 500 -reward_vocab "data/closure_vocab.json" -mask_answers 1 -truncate_mode "top_p" -top_p 0.5 -grad_clip 1
echo "-------------------------- top_p 0.2---------------------------------------------------------------------------------------------------"
python src/scripts/run.py -max_len 40 -data_path "data" -out_path "output/RL/exp_clvr_vqa_20000img_top_p" -model "lstm" -update_every 128 -agent "PPO" -K_epochs 20 -eps_clip 0.02 -lr 0.001 -word_emb_size 32 -hidden_size 64 -num_episodes_train 30000 -debug "0,20000" -lm_path "output/lm_model/model.pt" -reward "vqa" -reward_path "output/vqa_model_film/model.pt" -condition_answer "after_fusion" -num_episodes_test 500 -reward_vocab "data/closure_vocab.json" -mask_answers 1 -truncate_mode "top_p" -top_p 0.2 -grad_clip 1
echo "-------------------------- top_p 0.1---------------------------------------------------------------------------------------------------"
python src/scripts/run.py -max_len 40 -data_path "data" -out_path "output/RL/exp_clvr_vqa_20000img_top_p" -model "lstm" -update_every 128 -agent "PPO" -K_epochs 20 -eps_clip 0.02 -lr 0.001 -word_emb_size 32 -hidden_size 64 -num_episodes_train 30000 -debug "0,20000" -lm_path "output/lm_model/model.pt" -reward "vqa" -reward_path "output/vqa_model_film/model.pt" -condition_answer "after_fusion" -num_episodes_test 500 -reward_vocab "data/closure_vocab.json" -mask_answers 1 -truncate_mode "top_p" -top_p 0.1 -grad_clip 1