#!/usr/bin/env bash
python src/scripts/run.py -max_len 10 -data_path "data" -out_path "output/RL/50_img_len_10_pretrained" -model "lstm" -update_every 128 -agent "PPO" -K_epochs 20 -eps_clip 0.02 -lr 0.001 -word_emb_size 32 -hidden_size 64 -num_episodes_train 50000 -policy_path "output/lstmwordbatch_pretraining/SL_LSTM_32_64/model.pt" -debug "0,50" -lm_path "output/lm_model/model.pt" -num_truncated 10 -grad_clip 1

python src/scripts/run.py -max_len 10 -data_path "data" -out_path "output/RL/50_img_len_10_pretrained" -model "lstm" -update_every 128 -agent "PPO" -K_epochs 20 -eps_clip 0.02 -lr 0.001 -word_emb_size 32 -hidden_size 64 -num_episodes_train 50000 -policy_path "output/lstmwordbatch_pretraining/SL_LSTM_32_64/model.pt" -debug "0,50" -lm_path "output/lm_model/model.pt" -num_truncated 10 -grad_clip 2

python src/scripts/run.py -max_len 10 -data_path "data" -out_path "output/RL/50_img_len_10_pretrained" -model "lstm" -update_every 128 -agent "PPO" -K_epochs 20 -eps_clip 0.02 -lr 0.001 -word_emb_size 32 -hidden_size 64 -num_episodes_train 50000 -policy_path "output/lstmwordbatch_pretraining/SL_LSTM_32_64/model.pt" -debug "0,50" -lm_path "output/lm_model/model.pt" -num_truncated 20 -grad_clip 1

python src/scripts/run.py -max_len 10 -data_path "data" -out_path "output/RL/50_img_len_10_pretrained" -model "lstm" -update_every 128 -agent "PPO" -K_epochs 20 -eps_clip 0.02 -lr 0.001 -word_emb_size 32 -hidden_size 64 -num_episodes_train 50000 -policy_path "output/lstmwordbatch_pretraining/SL_LSTM_32_64/model.pt" -debug "0,50" -lm_path "output/lm_model/model.pt" -num_truncated 20 -grad_clip 2

python src/scripts/run.py -max_len 10 -data_path "data" -out_path "output/RL/50_img_len_10_pretrained" -model "lstm" -update_every 128 -agent "PPO" -K_epochs 20 -eps_clip 0.02 -lr 0.001 -word_emb_size 32 -hidden_size 64 -num_episodes_train 50000 -policy_path "output/lstmwordbatch_pretraining/SL_LSTM_32_64/model.pt" -debug "0,50" -lm_path "output/lm_model/model.pt" -num_truncated 30 -grad_clip 1

python src/scripts/run.py -max_len 10 -data_path "data" -out_path "output/RL/50_img_len_10_pretrained" -model "lstm" -update_every 128 -agent "PPO" -K_epochs 20 -eps_clip 0.02 -lr 0.001 -word_emb_size 32 -hidden_size 64 -num_episodes_train 50000 -policy_path "output/lstmwordbatch_pretraining/SL_LSTM_32_64/model.pt" -debug "0,50" -lm_path "output/lm_model/model.pt" -num_truncated 30 -grad_clip 2