#!/bin/bash
python src/scripts/run.py -max_len 20 -data_path "data" -out_path "output/RL/reinforce_2000_img_len_20" -model "lstm" -update_every 64 -agent "REINFORCE" -K_epochs 20 -eps_clip 0.02 -lr 0.0001 -word_emb_size 32 -hidden_size 64 -num_episodes_train 50000 -lm_path "output/lm_model/model.pt" -num_truncated 50 -debug "0,2000" -grad_clip 1 -num_questions 8 -truncate_mode "sample_va" -num_episodes_test 200
python src/scripts/run.py -max_len 20 -data_path "data" -out_path "output/RL/reinforce_2000_img_len_20" -model "lstm" -update_every 64 -agent "REINFORCE" -K_epochs 20 -eps_clip 0.02 -lr 0.0001 -word_emb_size 32 -hidden_size 64 -num_episodes_train 50000 -lm_path "output/lm_model/model.pt" -num_truncated 10 -debug "0,2000" -grad_clip 1 -num_questions 8 -truncate_mode "proba_thr" -num_episodes_test 200 -p_th 0.05
python src/scripts/run.py -max_len 20 -data_path "data" -out_path "output/RL/reinforce_2000_img_len_20" -model "lstm" -update_every 64 -agent "REINFORCE" -K_epochs 20 -eps_clip 0.02 -lr 0.0001 -word_emb_size 32 -hidden_size 64 -num_episodes_train 50000 -lm_path "output/lm_model/model.pt" -num_truncated 10 -debug "0,2000" -grad_clip 1 -num_questions 8 -truncate_mode "proba_thr" -num_episodes_test 200 -p_th 0.1
python src/scripts/run.py -max_len 20 -data_path "data" -out_path "output/RL/reinforce_2000_img_len_20" -model "lstm" -update_every 64 -agent "REINFORCE" -K_epochs 20 -eps_clip 0.02 -lr 0.0001 -word_emb_size 32 -hidden_size 64 -num_episodes_train 50000 -lm_path "output/lm_model/model.pt" -num_truncated 10 -debug "0,2000" -grad_clip 1 -num_questions 8 -truncate_mode "proba_thr" -num_episodes_test 200 -p_th 0.5
python src/scripts/run.py -max_len 20 -data_path "data" -out_path "output/RL/reinforce_2000_img_len_20" -model "lstm" -update_every 64 -agent "REINFORCE" -K_epochs 20 -eps_clip 0.02 -lr 0.0001 -word_emb_size 32 -hidden_size 64 -num_episodes_train 50000 -policy_path "output/lstmwordbatch_pretraining/SL_LSTM_32_64/model.pt" -debug "0,2000" -num_questions 8 -num_truncated 87 -lm_path "output/lm_model/model.pt" -grad_clip 1 -truncate_mode "proba_thr" -num_episodes_test 200
python src/scripts/run.py -max_len 20 -data_path "data" -out_path "output/RL/reinforce_2000_img_len_20" -model "lstm" -update_every 64 -agent "REINFORCE" -K_epochs 20 -eps_clip 0.02 -lr 0.0001 -word_emb_size 32 -hidden_size 64 -num_episodes_train 50000 -policy_path "output/lstmwordbatch_pretraining/SL_LSTM_32_64/model.pt" -debug "0,2000" -num_questions 8 -num_truncated 87 -lm_path "output/lm_model/model.pt" -grad_clip 1 -truncate_mode "proba_thr" -num_episodes_test 200 -p_th 0.05
python src/scripts/run.py -max_len 20 -data_path "data" -out_path "output/RL/reinforce_2000_img_len_20" -model "lstm" -update_every 64 -agent "REINFORCE" -K_epochs 20 -eps_clip 0.02 -lr 0.0001 -word_emb_size 32 -hidden_size 64 -num_episodes_train 50000 -policy_path "output/lstmwordbatch_pretraining/SL_LSTM_32_64/model.pt" -debug "0,2000" -num_questions 8 -num_truncated 87 -lm_path "output/lm_model/model.pt" -grad_clip 1 -truncate_mode "proba_thr" -num_episodes_test 200 -p_th 0.1
python src/scripts/run.py -max_len 20 -data_path "data" -out_path "output/RL/reinforce_2000_img_len_20" -model "lstm" -update_every 64 -agent "REINFORCE" -K_epochs 20 -eps_clip 0.02 -lr 0.0001 -word_emb_size 32 -hidden_size 64 -num_episodes_train 50000 -policy_path "output/lstmwordbatch_pretraining/SL_LSTM_32_64/model.pt" -debug "0,2000" -num_questions 8 -num_truncated 87 -lm_path "output/lm_model/model.pt" -grad_clip 1 -truncate_mode "proba_thr" -num_episodes_test 200 -p_th 0.5
python src/scripts/run.py -max_len 20 -data_path "data" -out_path "output/RL/reinforce_2000_img_len_20" -model "lstm" -update_every 64 -agent "REINFORCE" -K_epochs 20 -eps_clip 0.02 -lr 0.0001 -word_emb_size 32 -hidden_size 64 -num_episodes_train 50000 -policy_path "output/lstmwordbatch_pretraining/SL_LSTM_32_64/model.pt" -debug "0,2000" -num_questions 8 -num_truncated 20 -lm_path "output/lm_model/model.pt" -grad_clip 1 -truncate_mode "sample_va" -num_episodes_test 200
python src/scripts/run.py -max_len 20 -data_path "data" -out_path "output/RL/reinforce_2000_img_len_20" -model "lstm" -update_every 64 -agent "REINFORCE" -K_epochs 20 -eps_clip 0.02 -lr 0.0001 -word_emb_size 32 -hidden_size 64 -num_episodes_train 50000 -policy_path "output/lstmwordbatch_pretraining/SL_LSTM_32_64/model.pt" -debug "0,2000" -num_questions 8 -num_truncated 30 -lm_path "output/lm_model/model.pt" -grad_clip 1 -truncate_mode "sample_va" -num_episodes_test 200
python src/scripts/run.py -max_len 20 -data_path "data" -out_path "output/RL/reinforce_2000_img_len_20" -model "lstm" -update_every 64 -agent "REINFORCE" -K_epochs 20 -eps_clip 0.02 -lr 0.0001 -word_emb_size 32 -hidden_size 64 -num_episodes_train 50000 -policy_path "output/lstmwordbatch_pretraining/SL_LSTM_32_64/model.pt" -debug "0,2000" -num_questions 8 -num_truncated 50 -lm_path "output/lm_model/model.pt" -grad_clip 1 -truncate_mode "sample_va" -num_episodes_test 200








